export const STYLES = {
  container: 'flex flex-col items-center h-full pt-10',
  header: 'flex w-[340px] flex-row justify-center items-center',
  backButton: 'absolute left-0 w-[20px] h-[20px]',
  progressContainer: 'w-[270px] ml-10 h-[20px]',
  cursor: 'w-[10px] h-[10px] left-[-2.5px] top-[22px] absolute',
  progressBar: 'flex flex-row gap-1 items-center h-full w-full overflow-hidden',
  progressDot: 'w-[6px] h-[12px] rounded-full opacity-50',
  remainingCount: 'text-sm text-[#ed7d2d]',
  questionCard:
    'flex flex-col justify-between py-8 pt-12 border-2 items-center  w-[370px] h-full mt-4 mb-3 rounded-[2rem] transition-transform duration-300 ease-in-out',
  questionContainer: 'flex flex-col flex-1 px-8 w-[350px] relative',
  questionText: 'text-3xl text-clip mb-4 font-semibold',
  choicesContainer: 'h-[350px] grow justify-center',
  choiceButton: 'py-6 px-4 rounded-xl w-full ',
  selectedChoiceButton: 'py-6 px-4 rounded-xl w-full border',
  choiceText: 'text-lg text-center ',
  sequenceItem: 'py-6 px-4 my-[5px] rounded-[8px] flex flex-row items-center',
  sequenceText: 'text-lg flex-1 text-[#9095a0]',
  sequenceControls: 'flex flex-row gap-2',
  sequenceButton: 'w-8 h-8 flex items-center justify-center rounded-full',
  activeSequenceItem: 'border',
  inactiveSequenceItem: 'border border-2',
  sequenceInstructions: 'text-sm mb-2',
  buttonContainer: 'flex gap-10 flex-row mb-10',
  dontKnowButton: 'px-6 py-5 rounded-2xl',
  dontKnowText: 'text-xl',
  confirmButton: 'border border-1 px-6 py-5 rounded-2xl',
  confirmText: 'text-xl',
  footer: 'w-full flex flex-row justify-between items-center border-t pt-2',
  footerText: 'text-sm',
  bottomBar: 'flex flex-row justify-around w-[350px] h-[50px] opacity-90 mb-5',
  actionButton: 'px-5 py-3 rounded-2xl',
  actionText: 'text-md text-white',
  feedbackOverlay:
    'fixed top-0 left-0 right-0 bottom-0 flex items-center justify-center z-50 bg-opacity-90',
  feedbackText: 'text-5xl font-bold text-white feedback-scale',
  correctFeedback: 'bg-[#1dd75b]',
  incorrectFeedback: 'bg-[#de3b40]',
} as const;
